name: تحميل الملف من الرابط وفك الضغط

on:
  push:
    branches:
      - الرئيسي # أو أي فرع ترغب بتفعيل سير العمل عليه
  workflow_dispatch: # لتفعيل الـ Workflow يدويًا

jobs:
  download-and-upload:
    runs-on: ubuntu-22.04 # تحديد إصدار Ubuntu الحالي (يمكن تغييره إلى ubuntu-24.04 لاحقًا)

    steps:
      # خطوة لعمل checkout للكود
      - name: Checkout code
        uses: actions/checkout@v2

      # خطوة لتحميل الملف من الرابط
      - name: Download file from URL
        run: |
          curl -L -o /tmp/your-file.zip https://opencartarab.com/a/4022

      # خطوة لفك ضغط الملف
      - name: Extract downloaded file
        run: |
          unzip /tmp/your-file.zip -d /tmp/extracted-files

      # خطوة رفع الملفات التي تم فك ضغطها إلى مستودع GitHub
      - name: Upload extracted files to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: extracted-files
          path: /tmp/extracted-files/
